name: integrity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  uuid: ^4.5.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Notifications & Alarms
  flutter_local_notifications: ^17.0.0
  record: ^6.2.0
  audioplayers: ^6.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  timezone: ^0.9.4
  device_info_plus: ^11.0.0
  android_intent_plus: ^5.1.4
  # AI Notes - Document Scan & OCR
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_language_id: ^0.11.0
  image: ^4.8.0
  flutter_timezone: ^5.0.2
  alarm: ^3.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/alarm.mp3
    - assets/alarm1.mp3
    - assets/alarm2.mp3
    # - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"